/** Shared dropdown options — anything with a finite set of valid values */

export const US_STATES: Array<{ code: string; name: string }> = [
  { code: "AL", name: "Alabama" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "NC", name: "North Carolina" },
  { code: "SC", name: "South Carolina" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "VA", name: "Virginia" },
  // rest of US for completeness
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "DC", name: "District of Columbia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SD", name: "South Dakota" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];

/** Common cities for GA/SC coastal sales — free text still allowed via datalist */
export const COMMON_CITIES = [
  "Savannah",
  "Pooler",
  "Richmond Hill",
  "Rincon",
  "Guyton",
  "Springfield",
  "Hinesville",
  "Statesboro",
  "Brunswick",
  "Tybee Island",
  "Wilmington Island",
  "Bloomingdale",
  "Port Wentworth",
  "Garden City",
  "Thunderbolt",
  "Bluffton",
  "Hilton Head Island",
  "Hardeeville",
  "Beaufort",
  "Charleston",
  "Summerville",
  "Mount Pleasant",
  "Atlanta",
  "Augusta",
  "Macon",
  "Columbus",
  "Other",
];

export const GA_SC_AHJ = [
  "Chatham County",
  "City of Savannah",
  "Effingham County",
  "Bryan County",
  "Liberty County",
  "Bulloch County",
  "Glynn County",
  "Beaufort County",
  "Jasper County",
  "Charleston County",
  "Berkeley County",
  "Dorchester County",
  "Other / TBD",
];

export const OFFSET_PRESETS = [
  { value: 0.7, label: "70% — lower system cost" },
  { value: 0.8, label: "80%" },
  { value: 0.9, label: "90%" },
  { value: 0.95, label: "95% — typical target" },
  { value: 1.0, label: "100% — full offset" },
  { value: 1.1, label: "110% — EV / future load headroom" },
];

export const BILL_PRESETS = [
  80, 100, 120, 150, 175, 200, 225, 250, 275, 300, 350, 400, 500, 600, 750, 1000,
];
