import type { ProposalProject } from "./types";

/** Rich demo portfolio — OpenSolar-shaped metrics, Enerflo-level presentation */
export const SAMPLE_PROJECTS: ProposalProject[] = [
  {
    id: "demo-1001",
    identifier: "os-demo-vaucluse",
    stage: "proposal",
    createdAt: "2026-06-28T14:00:00Z",
    updatedAt: "2026-07-12T10:30:00Z",
    validUntil: "2026-08-15",
    address: {
      street: "1847 Ocean View Drive",
      city: "Savannah",
      state: "GA",
      zip: "31406",
      country: "US",
      lat: 31.9784,
      lon: -81.0998,
      lines: ["1847 Ocean View Drive", "Savannah, GA 31406"],
    },
    contacts: [
      {
        id: "c1",
        fullName: "Marcus & Elena Whitfield",
        firstName: "Marcus",
        lastName: "Whitfield",
        email: "marcus.whitfield@email.com",
        phone: "(912) 555-0142",
      },
    ],
    primaryContact: {
      id: "c1",
      fullName: "Marcus & Elena Whitfield",
      firstName: "Marcus",
      lastName: "Whitfield",
      email: "marcus.whitfield@email.com",
      phone: "(912) 555-0142",
    },
    org: {
      id: "org-lumen",
      name: "Lumen Solar",
      phone: "(912) 555-8800",
      website: "https://lumensolar.example",
      about:
        "Premium residential solar design and installation. We engineer systems that look as good as they perform.",
      highlightColor: "#C9A227",
    },
    assignedRep: {
      id: "rep1",
      name: "Jordan Hale",
      email: "jordan@lumensolar.example",
      phone: "(912) 555-8801",
      scheduleUrl: "#",
      scheduleLabel: "Book a design review",
    },
    proposalMessage:
      "Your home is an excellent solar candidate. Production is modeled from NASA climate data at your coordinates (~4.7 peak sun hours/day) — not a national average template — sized to cover nearly all of your annual usage with financing that can lower monthly energy cost from day one.",
    source: "sample",
    tags: ["residential", "priority", "site-irradiance"],
    solarResource: {
      lat: 31.9784,
      lon: -81.0998,
      peakSunHoursAnnual: 4.73,
      peakSunHoursMonthly: [
        2.98, 3.61, 4.79, 5.95, 6.46, 6.19, 6.21, 5.6, 4.82, 4.11, 3.29, 2.64,
      ],
      specificYieldKwhPerKw: 1380,
      source: "NASA POWER climatology (2001–2020)",
      summary: "Your site · 4.7 peak sun hours/day avg · ~1,380 kWh/kW/year",
    },
    systems: [
      {
        id: "sys-a",
        name: "Signature",
        title: "Signature System · 9.60 kW",
        kwStc: 9.6,
        panelCount: 24,
        hasBattery: false,
        panelGroups: [
          {
            id: "g1",
            panels: 16,
            azimuth: 180,
            tilt: 22,
            orientation: "South",
            moduleCode: "REC Alpha Pure 400",
          },
          {
            id: "g2",
            panels: 8,
            azimuth: 225,
            tilt: 22,
            orientation: "Southwest",
            moduleCode: "REC Alpha Pure 400",
          },
        ],
        hardware: {
          modules: {
            code: "REC Alpha Pure 400",
            manufacturer: "REC",
            watts: 400,
            quantity: 24,
          },
          inverter: {
            code: "Enphase IQ8+",
            manufacturer: "Enphase",
            quantity: 24,
          },
        },
        production: {
          annualKwh: 12840,
          monthlyKwh: [720, 780, 980, 1180, 1320, 1380, 1420, 1340, 1180, 980, 800, 760],
          offsetPercent: 97,
          consumptionAnnualKwh: 13200,
          peakSunHours: 4.73,
          peakSunHoursMonthly: [
            2.98, 3.61, 4.79, 5.95, 6.46, 6.19, 6.21, 5.6, 4.82, 4.11, 3.29, 2.64,
          ],
          specificYield: 1380,
          solarResourceSource: "NASA POWER climatology (2001–2020)",
          solarResourceSummary:
            "Your site · 4.7 peak sun hours/day avg · ~1,380 kWh/kW/year",
        },
        financials: {
          systemPrice: 28800,
          netPrice: 20160,
          incentivesTotal: 8640,
          federalTaxCredit: 8640,
          paybackYears: 6.4,
          npv: 41200,
          irr: 14.2,
          roi: 218,
          costPerWatt: 3.0,
        },
        bills: {
          currentMonthly: 218,
          proposedMonthly: 28,
          currentAnnual: 2616,
          proposedAnnual: 336,
          firstYearSavings: 2280,
          twentyFiveYearSavings: 78400,
          utilityName: "Georgia Power",
        },
        paymentOptions: [
          {
            id: "cash",
            name: "Cash Purchase",
            type: "cash",
            totalCost: 28800,
            netCost: 20160,
            incentives: 8640,
            featured: true,
            description: "Own it outright. Strongest lifetime return.",
          },
          {
            id: "loan",
            name: "0% Down Loan",
            type: "loan",
            downPayment: 0,
            monthlyPayment: 142,
            termMonths: 240,
            apr: 4.99,
            totalCost: 28800,
            netCost: 20160,
            incentives: 8640,
            description: "Start saving immediately — payment often under your utility bill.",
          },
          {
            id: "lease",
            name: "Solar Lease",
            type: "lease",
            downPayment: 0,
            monthlyPayment: 99,
            termMonths: 300,
            description: "Lowest entry cost. Maintenance included.",
          },
        ],
        panelPlacementSummary: "24 × REC Alpha Pure 400 (portrait)",
        orientationSummary: "16 panels South @ 22° · 8 panels Southwest @ 22°",
      },
      {
        id: "sys-b",
        name: "Resilience",
        title: "Resilience System · 9.60 kW + 13.5 kWh",
        kwStc: 9.6,
        panelCount: 24,
        hasBattery: true,
        batteryKwh: 13.5,
        panelGroups: [
          {
            id: "g1",
            panels: 24,
            azimuth: 180,
            tilt: 22,
            orientation: "South",
            moduleCode: "REC Alpha Pure 400",
          },
        ],
        hardware: {
          modules: {
            code: "REC Alpha Pure 400",
            manufacturer: "REC",
            watts: 400,
            quantity: 24,
          },
          inverter: {
            code: "Enphase IQ8+",
            manufacturer: "Enphase",
            quantity: 24,
          },
          battery: {
            code: "Tesla Powerwall 3",
            kwh: 13.5,
            quantity: 1,
          },
        },
        production: {
          annualKwh: 12840,
          monthlyKwh: [720, 780, 980, 1180, 1320, 1380, 1420, 1340, 1180, 980, 800, 760],
          offsetPercent: 97,
          consumptionAnnualKwh: 13200,
        },
        financials: {
          systemPrice: 42800,
          netPrice: 29960,
          incentivesTotal: 12840,
          federalTaxCredit: 12840,
          paybackYears: 9.1,
          npv: 28600,
          irr: 10.4,
          roi: 162,
          costPerWatt: 4.46,
        },
        bills: {
          currentMonthly: 218,
          proposedMonthly: 22,
          currentAnnual: 2616,
          proposedAnnual: 264,
          firstYearSavings: 2352,
          twentyFiveYearSavings: 81200,
          utilityName: "Georgia Power",
        },
        paymentOptions: [
          {
            id: "cash-b",
            name: "Cash Purchase",
            type: "cash",
            totalCost: 42800,
            netCost: 29960,
            incentives: 12840,
            featured: true,
            description: "Solar + storage ownership with backup power.",
          },
          {
            id: "loan-b",
            name: "0% Down Loan",
            type: "loan",
            downPayment: 0,
            monthlyPayment: 198,
            termMonths: 240,
            apr: 5.49,
            totalCost: 42800,
            netCost: 29960,
            incentives: 12840,
            description: "Backup power with manageable monthly payments.",
          },
        ],
        panelPlacementSummary: "24 × REC Alpha Pure 400 + Powerwall 3",
        orientationSummary: "24 panels South @ 22°",
      },
    ],
    selectedSystemId: "sys-a",
  },
  {
    id: "demo-1002",
    stage: "negotiation",
    createdAt: "2026-06-10T09:00:00Z",
    updatedAt: "2026-07-10T16:00:00Z",
    validUntil: "2026-07-30",
    address: {
      street: "42 Magnolia Lane",
      city: "Pooler",
      state: "GA",
      zip: "31322",
      country: "US",
      lines: ["42 Magnolia Lane", "Pooler, GA 31322"],
    },
    contacts: [
      {
        id: "c2",
        fullName: "Diane Okonkwo",
        email: "diane.o@email.com",
        phone: "(912) 555-0199",
      },
    ],
    primaryContact: {
      id: "c2",
      fullName: "Diane Okonkwo",
      email: "diane.o@email.com",
      phone: "(912) 555-0199",
    },
    org: {
      id: "org-lumen",
      name: "Lumen Solar",
      phone: "(912) 555-8800",
      highlightColor: "#C9A227",
    },
    assignedRep: {
      name: "Jordan Hale",
      email: "jordan@lumensolar.example",
    },
    source: "sample",
    systems: [
      {
        id: "sys-c",
        name: "Essential",
        title: "Essential System · 7.20 kW",
        kwStc: 7.2,
        panelCount: 18,
        hasBattery: false,
        panelGroups: [
          {
            id: "g1",
            panels: 18,
            azimuth: 170,
            tilt: 18,
            orientation: "South",
            moduleCode: "Qcells Q.PEAK DUO 400",
          },
        ],
        hardware: {
          modules: {
            code: "Qcells Q.PEAK DUO 400",
            manufacturer: "Qcells",
            watts: 400,
            quantity: 18,
          },
          inverter: {
            code: "SolarEdge SE7600H",
            manufacturer: "SolarEdge",
            quantity: 1,
          },
        },
        production: {
          annualKwh: 9420,
          monthlyKwh: [540, 580, 720, 860, 980, 1020, 1050, 980, 860, 720, 580, 530],
          offsetPercent: 92,
          consumptionAnnualKwh: 10200,
        },
        financials: {
          systemPrice: 21600,
          netPrice: 15120,
          incentivesTotal: 6480,
          federalTaxCredit: 6480,
          paybackYears: 5.8,
          npv: 33800,
          costPerWatt: 3.0,
        },
        bills: {
          currentMonthly: 168,
          proposedMonthly: 24,
          currentAnnual: 2016,
          proposedAnnual: 288,
          firstYearSavings: 1728,
          twentyFiveYearSavings: 59200,
          utilityName: "Georgia Power",
        },
        paymentOptions: [
          {
            id: "loan-c",
            name: "0% Down Loan",
            type: "loan",
            monthlyPayment: 108,
            termMonths: 240,
            apr: 4.99,
            totalCost: 21600,
            netCost: 15120,
            incentives: 6480,
            featured: true,
          },
          {
            id: "cash-c",
            name: "Cash Purchase",
            type: "cash",
            totalCost: 21600,
            netCost: 15120,
            incentives: 6480,
          },
        ],
        orientationSummary: "18 panels South @ 18°",
      },
    ],
    selectedSystemId: "sys-c",
  },
  {
    id: "demo-1003",
    stage: "sold",
    createdAt: "2026-05-02T11:00:00Z",
    updatedAt: "2026-07-01T08:00:00Z",
    address: {
      street: "901 Habersham Street",
      city: "Savannah",
      state: "GA",
      zip: "31401",
      country: "US",
      lines: ["901 Habersham Street", "Savannah, GA 31401"],
    },
    contacts: [
      {
        id: "c3",
        fullName: "Robert Chen",
        email: "rchen@email.com",
        phone: "(912) 555-0110",
      },
    ],
    primaryContact: {
      id: "c3",
      fullName: "Robert Chen",
      email: "rchen@email.com",
      phone: "(912) 555-0110",
    },
    org: {
      id: "org-lumen",
      name: "Lumen Solar",
      phone: "(912) 555-8800",
      highlightColor: "#C9A227",
    },
    source: "sample",
    systems: [
      {
        id: "sys-d",
        name: "Urban",
        title: "Urban System · 6.40 kW",
        kwStc: 6.4,
        panelCount: 16,
        hasBattery: true,
        batteryKwh: 10,
        panelGroups: [
          {
            id: "g1",
            panels: 16,
            azimuth: 190,
            tilt: 25,
            orientation: "South",
            moduleCode: "REC Alpha Pure 400",
          },
        ],
        hardware: {
          modules: {
            code: "REC Alpha Pure 400",
            manufacturer: "REC",
            watts: 400,
            quantity: 16,
          },
          inverter: {
            code: "Enphase IQ8+",
            manufacturer: "Enphase",
            quantity: 16,
          },
          battery: {
            code: "Enphase IQ Battery 5P",
            kwh: 10,
            quantity: 2,
          },
        },
        production: {
          annualKwh: 8120,
          monthlyKwh: [460, 500, 620, 740, 840, 880, 900, 840, 740, 620, 500, 480],
          offsetPercent: 88,
          consumptionAnnualKwh: 9200,
        },
        financials: {
          systemPrice: 31200,
          netPrice: 21840,
          incentivesTotal: 9360,
          federalTaxCredit: 9360,
          paybackYears: 8.2,
          costPerWatt: 4.88,
        },
        bills: {
          currentMonthly: 142,
          proposedMonthly: 18,
          currentAnnual: 1704,
          proposedAnnual: 216,
          firstYearSavings: 1488,
          twentyFiveYearSavings: 51200,
          utilityName: "Georgia Power",
        },
        paymentOptions: [
          {
            id: "cash-d",
            name: "Cash Purchase",
            type: "cash",
            totalCost: 31200,
            netCost: 21840,
            incentives: 9360,
            featured: true,
          },
        ],
      },
    ],
    selectedSystemId: "sys-d",
  },
  {
    id: "demo-1004",
    stage: "design",
    createdAt: "2026-07-08T15:00:00Z",
    updatedAt: "2026-07-13T12:00:00Z",
    address: {
      street: "15 Riverwalk Court",
      city: "Richmond Hill",
      state: "GA",
      zip: "31324",
      country: "US",
      lines: ["15 Riverwalk Court", "Richmond Hill, GA 31324"],
    },
    contacts: [
      {
        id: "c4",
        fullName: "Amanda Torres",
        email: "amanda.t@email.com",
        phone: "(912) 555-0177",
      },
    ],
    primaryContact: {
      id: "c4",
      fullName: "Amanda Torres",
      email: "amanda.t@email.com",
      phone: "(912) 555-0177",
    },
    org: {
      id: "org-lumen",
      name: "Lumen Solar",
      phone: "(912) 555-8800",
      highlightColor: "#C9A227",
    },
    source: "sample",
    systems: [
      {
        id: "sys-e",
        name: "Draft",
        title: "Draft Design · 11.20 kW",
        kwStc: 11.2,
        panelCount: 28,
        hasBattery: false,
        panelGroups: [
          {
            id: "g1",
            panels: 28,
            azimuth: 175,
            tilt: 20,
            orientation: "South",
            moduleCode: "REC Alpha Pure 400",
          },
        ],
        hardware: {
          modules: {
            code: "REC Alpha Pure 400",
            manufacturer: "REC",
            watts: 400,
            quantity: 28,
          },
          inverter: {
            code: "Enphase IQ8+",
            manufacturer: "Enphase",
            quantity: 28,
          },
        },
        production: {
          annualKwh: 14800,
          monthlyKwh: [840, 900, 1140, 1360, 1520, 1600, 1640, 1540, 1360, 1140, 920, 840],
          offsetPercent: 100,
          consumptionAnnualKwh: 14500,
        },
        financials: {
          systemPrice: 33600,
          netPrice: 23520,
          incentivesTotal: 10080,
          federalTaxCredit: 10080,
          paybackYears: 6.9,
          costPerWatt: 3.0,
        },
        bills: {
          currentMonthly: 264,
          proposedMonthly: 12,
          currentAnnual: 3168,
          proposedAnnual: 144,
          firstYearSavings: 3024,
          twentyFiveYearSavings: 104000,
          utilityName: "Georgia Power",
        },
        paymentOptions: [
          {
            id: "loan-e",
            name: "0% Down Loan",
            type: "loan",
            monthlyPayment: 168,
            termMonths: 240,
            apr: 4.99,
            totalCost: 33600,
            netCost: 23520,
            incentives: 10080,
            featured: true,
          },
        ],
      },
    ],
    selectedSystemId: "sys-e",
  },
];

/** Minimal OpenSolar-shaped export for import demos */
export const SAMPLE_OPENSOLAR_JSON = [
  {
    id: 62854,
    name: "Demo Solar Co.",
    logo_public_url: null,
    sales_phone_number: "(800) 555-0199",
    company_website: "https://example.com",
    color_highlight: "#1B4F72",
    country_iso2: "US",
    projects: [
      {
        id: 99001,
        identifier: "imported-opensolar-1",
        address: "220 Coastal Highway",
        locality: "Tybee Island",
        state: "GA",
        zip: "31328",
        country_iso2: "US",
        lat: 32.0002,
        lon: -80.8456,
        stage: 2,
        created_date: "2026-07-01T10:00:00Z",
        modified_date: "2026-07-11T10:00:00Z",
        valid_until_date: "2026-08-01",
        contacts: [
          {
            id: 501,
            display: "Sarah Nguyen",
            full_name: "Sarah Nguyen",
            first_name: "Sarah",
            family_name: "Nguyen",
            email: "sarah.n@email.com",
            phone: "(912) 555-0166",
          },
        ],
        assigned_team_member: {
          id: 10,
          display: "Alex Rivera",
          email: "alex@demosolar.example",
          schedule_meeting_url: "#",
          schedule_meeting_label: "Schedule a call",
        },
        usage_annual_or_guess: 11000,
        proposal_data: {
          colors: {
            textColor: "#1a1a1a",
            highlightColor: "#1B4F72",
          },
          address_over_two_lines: ["220 Coastal Highway", "Tybee Island, GA 31328"],
          proposal_message:
            "Based on your usage and roof geometry, this system is sized for near-full offset with room for future EV charging.",
          systems: [
            {
              title: "System 1 (8.40 kW)",
              name: "System 1",
              has_battery: false,
              battery_total_kwh: 0,
              systemKwStc: "8.400",
              systemOutputAnnualkWh: "11,240",
              systemPaybackYear: "6.1",
              systemNetPresentValue: "$36,800",
              systemIrr: "13.5",
              systemReturnOnInvestment: "205",
              panelOrientations: "21 panels facing South at 18°",
              systemPanelPlacement: "21 x REC Alpha Pure 400 (portrait)",
              moduleCodes: "REC Alpha Pure 400",
              inverterCodes: "Enphase IQ8+",
              batteryCodes: "",
              output_monthly_json: "[640,700,880,1040,1160,1220,1260,1180,1040,860,700,660]",
              data: {
                pricing: {
                  system_price: 25200,
                  price_including_tax: 25200,
                  incentive_to_customer: 7560,
                  payback: 6.1,
                  npv: 36800,
                },
                payment_options: [
                  {
                    id: "po1",
                    name: "Cash",
                    payment_type: "cash",
                    price_including_tax: 25200,
                    down_payment: 25200,
                    featured: true,
                  },
                  {
                    id: "po2",
                    name: "Loan 20yr",
                    payment_type: "loan",
                    monthly_payment: 128,
                    term_months: 240,
                    apr: 5.49,
                    down_payment: 0,
                    price_including_tax: 25200,
                  },
                ],
                module: {
                  code: "REC Alpha Pure 400",
                  manufacturer_name: "REC",
                  watts: 400,
                  quantity: 21,
                },
                inverters: [
                  {
                    code: "Enphase IQ8+",
                    manufacturer_name: "Enphase",
                    quantity: 21,
                  },
                ],
                batteries: [],
                bills: {
                  annual_utility_bill_without_solar: 2280,
                  annual_utility_bill_with_solar: 240,
                  utility_name: "Georgia Power",
                },
                consumption: {
                  annual_kwh: 11000,
                  self_consumption_percentage: 94,
                },
                site: {
                  azimuth: 180,
                  tilt: 18,
                },
              },
            },
          ],
        },
      },
    ],
  },
];
